version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "09:00"
      timezone: "Europe/Amsterdam"
    groups:
      npm:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: composer
    directory: /
    schedule:
      interval: daily
      time: "09:00"
      timezone: "Europe/Amsterdam"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      composer:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
