name: Marzun - Laravel CI

on:
  pull_request:
    # Run on PR's for master when Opened, Reopened or Synchronized.
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize

jobs:
  cerberos-laravel-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: xdebug

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Setup Nova License Information
        env:
          NOVA_USERNAME: ${{ secrets.NOVA_USERNAME }}
          NOVA_PASSWORD: ${{ secrets.NOVA_PASSWORD }}
        if: env.NOVA_USERNAME != '' && env.NOVA_PASSWORD != ''
        run: composer config "http-basic.nova.laravel.com" "${{ secrets.NOVA_USERNAME }}" "${{ secrets.NOVA_PASSWORD }}"

      - name: The PHP Security Checker
        uses: symfonycorp/security-checker-action@v4

      - name: Install Composer Dependencies
        run: composer install --no-ansi --no-interaction --no-progress --optimize-autoloader

      - name: Run Refactor and Lint
        run: composer fix

      - name: Commit and Push Changes
        env:
          CI_USER: ${{ secrets.MARZUN_USER }}
          CI_EMAIL: ${{ secrets.MARZUN_EMAIL }}
        run: |
          git config --local user.email "$CI_EMAIL"
          git config --local user.name "$CI_USER"

          git add -A

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "CI: Refactor and Lint code"

            git push
          fi

      - name: Generate Key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 755 storage bootstrap/cache

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install NPM packages
        run: npm install

      - name: Build NPM packages
        run: npm run prod

      - name: Execute Tests
        run: composer test
